import PDFDocument from "pdfkit"

export async function generateNumerologyPDF(data: {
  name: string
  dob: string
  moolank: number
  bhagyank: number
  aiAnalysis: string
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 })
    const buffers: Buffer[] = []

    doc.on("data", (chunk) => buffers.push(chunk))
    doc.on("end", () => resolve(Buffer.concat(buffers)))
    doc.on("error", reject)

    // Header
    doc.fontSize(24).fillColor("#4F46E5").text("Numero", { align: "center" })
    doc.moveDown(0.5)
    doc.fontSize(12).fillColor("#666666").text("Next Gen Numerology Report", { align: "center" })
    doc.moveDown(2)

    // Profile Info
    doc.fontSize(14).fillColor("#000000").text(`Report for: ${data.name}`)
    doc.fontSize(12).text(`Date of Birth: ${data.dob}`)
    doc.moveDown(1)

    // Numbers
    doc.fontSize(16).text(`Moolank: ${data.moolank}   |   Bhagyank: ${data.bhagyank}`)
    doc.moveDown(2)

    // AI Analysis
    doc.fontSize(14).text("Cosmic Analysis", { underline: true })
    doc.moveDown(1)
    doc.fontSize(11).lineGap(4).text(data.aiAnalysis, { align: "justify" })

    // Footer
    doc.moveDown(4)
    doc.fontSize(10).fillColor("#999999").text("Generated by Numero AI", { align: "center" })

    doc.end()
  })
}
